project:
  type: website
  output-dir: docs

website:
  title: "Winson Y. Chen"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Psychometrics Portfolio"
        href: Psychometrics_Portfolio.qmd
  
  sidebar:
      title: "Psychometrics Portfolio"
      style: "docked"
      background: "dark"
      contents: 
        - text: "Introduction"
          href: Psychometrics_Portfolio.qmd
        - text: "---"
        - text: "Project 1 - Foundational Analyses Using Multiple-Choice Response Data"
          href: project_1.qmd
        - text: "---"
        - text: "Project 2 - PISA Data Wrangling and Vertical Scaling"
          href: project_2.qmd

format:
  html:
    theme: minty
    css: styles.css
    toc: true



