project:
  type: website
  output-dir: docs

website:
  title: "Winson Y. Chen"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Psychometrics_Portfolio.qmd
format:
  html:
    theme: minty
    css: styles.css
    toc: true



