---
title: "Psychometrics Portfolio"
toc: true
format: html
---

---

## Introduction

This portfolio is my attempt to catalog and showcase the various kinds of analyses that a psychometrician might perform with different kinds of data in different fields. The portfolio is structured as a series of projects; each involves taking a particular real-world dataset and running a comprehensive set of analyses which are appropriate for the properties of the data and the goals of stakeholders. All analyses are performed using the R programming language and the RStudio integrated development environment (IDE). 

This portfolio is also intended to be an open educational resource (OER) and can be used by anyone who wants to learn how to conduct psychometric analyses in R. This portfolio is far from ideal for self-study; it is neither highly self-contained nor highly expository, as would be expected in a textbook. Nevertheless, I hope that whoever reads this portfolio can find some value in the project/case study structure.  

The inspiration for this portfolio stems from my observation that, while there are a large number of excellent resources on the theory of psychometrics and applications in R, there are few resources that capture what the actual work of a psychometrician might look like in the form of projects. In my own learning, I have found that it is easy to get lost in theory without a clear sense of direction or indication as to whether one is actually learning. Furthermore, it can be very daunting to learn sophisticated methods and to keep track of what one has seen and understood. Creating this portfolio has been helpful for me in these respects. Another inspiration for this portfolio is the book "Psychometrics in Exercises using R and RStudio" by Anna Brown, which I found to be especially helpful in my learning, and which shares many of the same design principles as this portfolio. 

---

## Reproducibility

This portfolio was designed with reproducibility in mind. Reproducibility asks the following question: given the *same data* and the same methods, can an independent researcher obtain the *same results*, at a potentially later time? Reproducibility is often confused with replicability, which asks a different question: given a *new dataset* and the same methods, can an independent researcher obtain *similar results*? Replicability is often more scientifically interesting, but it is of theoretical rather than pragmatic concern; a replication failure may undermine a potential scientific theory. Reproducibility, on the other hand, is an essential practice for reporting and making decisions based on the results of analyses; a reproducibility failure undermines the transparency and trustworthiness of the results. 

*For those who simply wish to follow along with the analyses in this portfolio*, the reproducibility elements included in each project are likely unnecessary. Simply load the required packages and run the code. In most cases, the exact same results should appear. 

*For those who wish to reproduce the analyses almost exactly*, this portfolio utilizes the `{renv}` package (Ushey & Wickham, 2026), which creates reproducible environments for R projects. `{renv}` works by creating a project library that contains only the packages used in this portfolio. Additionally, `{renv}` creates a lockfile that contains the specific versions of every package used, as well as the repositories where the package versions are stored. The Comprehensive R Archive Network (CRAN) is the most popular repository; however, CRAN only stores the latest versions of packages. Instead, the `{renv}` packages uses the Posit Public Package Manager (P3M), as it stores older package versions. P3M has an additional benefit for reproducibility, which is that it stores *daily snapshots* of CRAN; this means that one can load the exact same package versions that were used by the author of the analyses on the day that the analyses were originally performed. 

To reproduce the analyses, I recommend the following steps: 

1. Clone the github repository for the portfolio website by running `git clone https://github.com/wyck-psych/wyck-psych.github.io.git` in the terminal.
2. Change the directory to the cloned project folder by typing `cd` followed by a space in the terminal and then dragging the cloned project folder into the terminal window. Most terminals will auto-fill the correct path to the project folder. Typically on Windows, the cloned project folder ends up in your `\Users` folder. Then run the full command, which will look something like `cd C:\Users\winso\wyck-psych.github.io`. 
3. Once the directory is set to the cloned project folder, run `rig rstudio renv.lock` in the terminal. This tells `rig` to open RStudio using the R version recorded in the `renv.lock` file. If that R version is not currently installed, `rig` will prompt you to install it. 
4. Once the project is opened in RStudio, run `renv::restore()` in the R console. This will install the exact date-snapshotted package versions into the project library. 
5. Once the packages are restored, the entire portfolio can be reproduced by running `quarto render` in RStudio's built-in terminal (Tools → Terminal). 

I recommend using a tool such as `rig` (an R installation manager which allows for switching between multiple versions of R) to load the exact R version recorded in the `renv.lock` file because `{renv}` may run into issues if a different version of R is used. To avoid headaches, it is easier to load the exact R version recorded using `rig`. 

---

