<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Project 1 - Foundational Analyses using Multiple-Choice Response Data from an Achievement Test – Winson Y. Chen</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-de63f62b328812d8e578a4d74e282472.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-b0f478263e242d87cba2e1790d46822e.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar docked nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Winson Y. Chen</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./Psychometrics_Portfolio.html" aria-current="page"> 
<span class="menu-text">Psychometrics Portfolio</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./project_1.html">Project 1 - Foundational Analyses using Multiple-Choice Response Data from an Achievement Test</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Psychometrics_Portfolio.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
        <li class="px-0"><hr class="sidebar-divider hi "></li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./project_1.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Project 1 - Foundational Analyses using Multiple-Choice Response Data from an Achievement Test</span></a>
  </div>
</li>
        <li class="px-0"><hr class="sidebar-divider hi "></li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./project_2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Project 2 - TBD</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#dataset-preparation-and-preliminary-inspection" id="toc-dataset-preparation-and-preliminary-inspection" class="nav-link" data-scroll-target="#dataset-preparation-and-preliminary-inspection">Dataset Preparation and Preliminary Inspection</a></li>
  <li><a href="#classical-reliability-and-item-analysis" id="toc-classical-reliability-and-item-analysis" class="nav-link" data-scroll-target="#classical-reliability-and-item-analysis">Classical Reliability and Item Analysis</a></li>
  <li><a href="#classical-distractor-analysis" id="toc-classical-distractor-analysis" class="nav-link" data-scroll-target="#classical-distractor-analysis">Classical Distractor Analysis</a></li>
  <li><a href="#optimal-scaling" id="toc-optimal-scaling" class="nav-link" data-scroll-target="#optimal-scaling">Optimal Scaling</a></li>
  <li><a href="#dimensionality-analysis" id="toc-dimensionality-analysis" class="nav-link" data-scroll-target="#dimensionality-analysis">Dimensionality Analysis</a></li>
  <li><a href="#item-response-theory-analysis" id="toc-item-response-theory-analysis" class="nav-link" data-scroll-target="#item-response-theory-analysis">Item Response Theory Analysis</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Project 1 - Foundational Analyses using Multiple-Choice Response Data from an Achievement Test</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<hr>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>The goal of this project is to analyze data collected from a multiple-choice achievement test. This data format is common within educational measurement, and contains one observation (row) per test-taker and one column per item, with each cell containing an unscored item response.</p>
<p>In this project, we will be analyzing the <em>Homeostasis Concept Inventory</em> (HCI) (McFarland et al., 2017), which is a 20-item multiple-choice test designed to measure undergraduate students’ understanding of the homeostasis concept. The HCI was developed through an iterative process which involved identifying common student misconceptions through think-aloud interviews and expert feedback, and developing distractors based on these misconceptions.</p>
<p>The dataset <code>HCIdata</code> is part of the <code>{ShinyItemAnalysis}</code> R package (Martinková &amp; Drabinová, 2018) and contains N=669 observations which were collected as part of the validation process for the final version of the HCI (McFarland et al., 2017). Notably, the dataset contains both the scored and unscored item responses, which allows for distractor analysis, as well as matching variables such as gender and minority membership, which allows for differential item functioning (DIF) analyses.</p>
<p>The <code>HCIdata</code> dataset contains 49 variables. The first 20 variables (1-20) are the unscored item responses which are recorded as A/B/C/D. The next 20 variables (21-40) are the scored item responses which are recorded as 0/1. The next variable (41) is the total/sum score. The last 8 variables (42-49) are demographic variables including gender, plans to major in the life sciences, class level/year in college, ethnicity, minority membership, English as the student’s first language, course type, and type of school. A complete description of this dataset can be found in the documentation for the <code>{ShinyItemAnalysis}</code> package (Martinková &amp; Drabinová, 2018) and additional information can also be found in the validation study for the HCI (McFarland et al., 2017).</p>
<hr>
</section>
<section id="dataset-preparation-and-preliminary-inspection" class="level2">
<h2 class="anchored" data-anchor-id="dataset-preparation-and-preliminary-inspection">Dataset Preparation and Preliminary Inspection</h2>
<p>First, the dataset and the required R packages were loaded into RStudio, and variables from the dataset were extracted to facilitate analysis. The dataset contained no missing values, so no treatment of missing values is needed.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="do">### Load the dataset and required packages</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ShinyItemAnalysis)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(psych)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"HCIdata"</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="do">### Extract variables to facilitate analysis</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>items_unscored <span class="ot">&lt;-</span> HCIdata[ , <span class="dv">1</span><span class="sc">:</span><span class="dv">20</span>]</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>items_scored <span class="ot">&lt;-</span> HCIdata[ ,<span class="dv">21</span><span class="sc">:</span><span class="dv">40</span>]</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>total_scores <span class="ot">&lt;-</span> HCIdata<span class="sc">$</span>total</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Before performing any analyses, a preliminary inspection of the total score distribution provides a useful overview of the instrument’s performance and suitability for subsequent analyses. This can be done by examining a histogram and descriptive statistics of the total scores. Some key issues to look for include: excessive skewness (which indicates a floor or ceiling effect), multimodality (which may indicate multidimensionality or distinct subgroups in the sample), and insufficient variability in scores (which can attenuate or destabilize estimates due to restriction of range; this may be indicated by a large positive kurtosis).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(total_scores)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="project_1_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" style="width:75.0%"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">describe</span>(total_scores)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   vars   n  mean   sd median trimmed  mad min max range  skew kurtosis   se
X1    1 669 12.13 3.65     12   12.22 4.45   3  20    17 -0.17    -0.68 0.14</code></pre>
</div>
</div>
<p><em>Overall, the total score distribution looks healthy. The mean of 12.13 indicates that the average student scored roughly 60.7%, which suggests that the difficulty of the test is well-aligned with the target population. The skewness of -0.17 is very small and indicates no ceiling or floor effects. The kurtosis of -0.68 indicates that the distribution is slightly platykurtic (flatter peak/thinner tails), which is desirable for differentiating students across the middle range of the score distribution. Lastly, the histogram and the standard deviation of 3.65 suggests that there is sufficient variation in the total scores.</em></p>
<hr>
</section>
<section id="classical-reliability-and-item-analysis" class="level2">
<h2 class="anchored" data-anchor-id="classical-reliability-and-item-analysis">Classical Reliability and Item Analysis</h2>
<p>The internal consistency reliability of the composite scores may be estimated using the coefficient alpha based on Pearson correlations (Phi coefficients). Additionally, since the items are dichotomously scored but are hypothesized to reflect an underlying normally distributed attribute, it may be helpful to estimate the ordinal alpha based on tetrachoric correlations, which represents the hypothetical reliability of the underlying attribute scores.</p>
<p>Both the Pearson correlation (Phi coefficient) and the tetrachoric correlation depend on the item difficulties. Both methods most accurately reflect the true linear relationship when the item difficulties are close to <em>p</em> = 0.5 (the mean of the underlying attribute distribution). When the item difficulties are closer to the extremes, the Phi coefficient is known to be attenuated (biased low), and the tetrachoric correlation remains unbiased but is less precise (larger standard errors).</p>
<p>It is useful to report both the coefficient alpha and the ordinal alpha for two reasons. The first reason is the difference in interpretation, which was briefly mentioned above. The coefficient alpha is an estimate of the reliability of the <em>composite scores</em> and reflects the reliability of the instrument as it is operationally scored and used. The ordinal alpha is an estimate of the reliability of the <em>underlying attribute distribution</em>, which reflects the theoretical reliability of measurement if the underlying attribute could be measured without information loss from being dichotomously scored. The second reason for reporting both estimates is that the difference between the estimates itself provides useful diagnostic information. If the ordinal alpha is not much higher than the coefficient alpha, then this suggests that there is little information loss from dichotomous scoring. Conversely, a substantial gap suggests that the item set includes more extreme difficulty values, and that meaningful information is loss by dichotomous scoring.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="do">### Coefficient alpha using Pearson correlations</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">alpha</span>(items_scored)[<span class="fu">c</span>(<span class="st">"total"</span>, <span class="st">"feldt"</span>)]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>$total
 raw_alpha std.alpha   G6(smc) average_r      S/N       ase      mean        sd
 0.7161644 0.7215166 0.7300311 0.1146869 2.590878 0.0158408 0.6064275 0.1825975
  median_r
 0.1205056

$feldt

   95% confidence boundaries (Feldt)
 lower alpha upper
  0.68  0.72  0.75</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="do">### Ordinal alpha using tetrachoric correlations</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>tetra <span class="ot">&lt;-</span> <span class="fu">tetrachoric</span>(items_scored)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">alpha</span>(tetra<span class="sc">$</span>rho)[<span class="fu">c</span>(<span class="st">"total"</span>, <span class="st">"feldt"</span>)]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>$total
 raw_alpha std.alpha   G6(smc) average_r      S/N  median_r
 0.8295802 0.8295802 0.8587097 0.1957491 4.867863 0.2072622

$feldt

   95% confidence boundaries (Feldt)
 lower alpha upper
   0.7  0.83  0.92</code></pre>
</div>
</div>
<p>The coefficient alpha estimate is 0.72 (95% CI [.68, .75]) and the ordinal alpha estimate is 0.83 (95% CI [.70, .92]). The difference is fairly substantial and suggests that the item set contains items with extreme difficulty values, and that there is meaningful information loss from dichotomous scoring. Furthermore, the width of the confidence interval for the ordinal alpha estimate is 0.22, compared to 0.07 for the coefficient alpha estimate. This is consistent with the tetrachoric correlation being a less precise reflection of the true linear relationship when the item difficulty values are extreme, as mentioned earlier.</p>
<p>The internal consistency of the composite scores likely falls within the “acceptable” range according to the recommendations of Nunnally &amp; Bernstein (1994). However, given that the instrument was designed to measure a single construct, this level of internal consistency is not particularly strong. Additionally, the recommendation by Nunnally is for early-stage research and classroom practice, and is below levels recommended for high-stakes decisions. Thus, the instrument is recommended for use in classroom settings, but should not be used as the sole basis for high-stakes decisions.</p>
<p>Next, the classical item difficulty, discrimination, and alpha-if-dropped are calculated and summarized in the table below. For item discrimination, both the item-total and the item-rest correlations are reported as point-biserial correlations, consistent with standard practice in classical item analysis.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>CTT_results <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>                 <span class="at">difficulty =</span> <span class="fu">round</span>(<span class="fu">colMeans</span>(items_scored), <span class="dv">3</span>),</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">discrimination_IT =</span> <span class="fu">round</span>(<span class="fu">ItemAnalysis</span>(items_scored)<span class="sc">$</span>RIT, <span class="dv">3</span>),</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>                 <span class="at">discrimination_IR =</span> <span class="fu">round</span>(<span class="fu">ItemAnalysis</span>(items_scored)<span class="sc">$</span>RIR, <span class="dv">3</span>),</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>                 <span class="at">alpha_drop =</span> <span class="fu">round</span>(<span class="fu">alpha</span>(items_scored)<span class="sc">$</span>alpha.drop<span class="sc">$</span>raw_alpha, <span class="dv">3</span>)</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>                           )</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>CTT_results</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     difficulty discrimination_IT discrimination_IR alpha_drop
QR1       0.695             0.410             0.298      0.704
QR2       0.750             0.334             0.222      0.711
QR3       0.848             0.430             0.344      0.702
QR4       0.399             0.305             0.177      0.715
QR5       0.445             0.390             0.265      0.707
QR6       0.359             0.458             0.345      0.700
QR7       0.541             0.240             0.106      0.722
QR8       0.703             0.440             0.330      0.701
QR9       0.429             0.344             0.217      0.712
QR10      0.641             0.387             0.267      0.707
QR11      0.770             0.397             0.293      0.705
QR12      0.577             0.421             0.300      0.704
QR13      0.601             0.477             0.363      0.698
QR14      0.755             0.441             0.339      0.701
QR15      0.435             0.431             0.311      0.703
QR16      0.604             0.484             0.371      0.697
QR17      0.291             0.173             0.049      0.725
QR18      0.789             0.506             0.416      0.695
QR19      0.779             0.455             0.358      0.700
QR20      0.717             0.443             0.336      0.701</code></pre>
</div>
</div>
<p>Notably, item 17 has very low discrimination (RIR = .049) as well as being a challenging item (<em>p</em> = .291). This indicates that item 17 is highly problematic, since individuals who correctly answered the item were not meaningfully more likely to have a higher total score. This is consistent with item QR17 having an alpha-if-dropped of 0.725, which is higher than the overall coefficient alpha estimate. Thus, item 17 is recommended for revision.</p>
<p>Additionally, item 7 (<em>p</em> = .541, RIR = .106, <span class="math inline">\(\alpha_{drop}\)</span> = .722) and item 4 (<em>p</em> = .399, RIR = .177, <span class="math inline">\(\alpha_{drop}\)</span> = .715) have low discrimination which is not attributable to floor or ceiling effects. Thus, these two items may also warrant revision.</p>
<p><em>In conclusion, the classical reliability analysis suggests that the internal consistency of the total scores likely falls within the “acceptable” range according to the recommendations of Nunnally &amp; Bernstein (1994). Furthermore, the difference between the coefficient alpha and the ordinal alpha suggests that there is meaningful information loss from dichotomous scoring. Additionally, the classical item analysis suggests that item 17, item 7, and item 4 have poor discrimination and may benefit from revision, in order of importance.</em></p>
<hr>
</section>
<section id="classical-distractor-analysis" class="level2">
<h2 class="anchored" data-anchor-id="classical-distractor-analysis">Classical Distractor Analysis</h2>
<p>Before performing distractor analysis, there is a minor issue with the <code>HCIdata</code> dataset that needs to be corrected. Item 5 (A5) should have four response options (A/B/C/D). However, looking at the dataset, two entries have been incorrectly coded as lowercase “c” rather than uppercase “C”, resulting in the variable having 5 factor levels (A/B/C/c/D). This can be easily corrected using the <code>fct_recode()</code> function in the <code>{forcats}</code> package, which is part of the tidyverse family of R packages.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Load the forcats package</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(forcats)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="do">## Correct the data entry issue for item 5</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>items_unscored<span class="sc">$</span>A5 <span class="ot">&lt;-</span> <span class="fu">fct_recode</span>(items_unscored<span class="sc">$</span>A5, <span class="st">"C"</span> <span class="ot">=</span> <span class="st">"c"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Now the two factor levels have been merged. Looking at the dataset, item A5 now has 4 factor levels (A/B/C/D), which is correct. Note that not all items have 4 factor levels; the majority have either 3 or 4 factor levels, with a few items having 5 factor levels. There are no additional issues with the dataset, so we may proceed with distractor analysis.</p>
<p>Distractor analysis may be divided into “classical” and “model-based” approaches. This section covers classical distractor analysis, while a later section will cover model-based approaches such as the nominal response model (NRM). Classical distractor analysis primarily involves examining statistics such as the proportions of test-takers who select each distractor and the point-biserial or biserial correlations between each distractor and the total scores. The primary goal of classical distractor analysis is to guide item development by identifying non-functioning or non-discriminating distractors.</p>
<p>Non-functioning distractors are distractors which are selected by a very low percentage of test-takers. A common rule-of-thumb is that distractors which are selected by less than 5% of test-takers are non-functioning. However, an exception to this rule can be made for very easy items. For instance, for a multiple-choice item in which 85% of test-takers chose the correct answer, it is likely that many of the distractors would be considered non-functioning under the 5% rule. However, such distractors are not necessarily problematic, and such items can still have good discrimination and be useful for content coverage purposes.</p>
<p>Non-discriminating distractors are distractors which are equally likely to be selected across the total score range. Good distractors test for misconceptions which are more common in test-takers with a lower total score. As total score increases, test-takers are expected to not have as many misconceptions, and thus should be less likely to select the distractors. If a distractor is roughly equally likely to be selected by all test-takers, no matter their total score, then this suggests that the functioning of the distractor may be unrelated to the construct of interest. For instance, the distractor may be selected due to confusing language or an unintentional cue in the item stem. Typically, the non-discriminating distractors of interest are those which are not also non-functioning, otherwise they would be simply considered non-functioning.</p>
<p>An effective and efficient way to screen for non-functioning and non-discriminating distractors is to examine <em>trace plots</em>, which are also called <em>distractor plots</em>. Distractor plots can be created using the <code>plotDistractorAnalysis()</code> function in the <code>{ShinyDataAnalysis}</code> package. To make the plots look a little nicer, the <code>{ggplot2}</code> and <code>{patchwork}</code> packages are also used.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Load packages</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(patchwork)</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="do">## Create the distractor plots for all 20 items</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>distractor_plots <span class="ot">&lt;-</span> <span class="fu">plotDistractorAnalysis</span>(</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>                        <span class="at">Data =</span> items_unscored, </span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>                        <span class="at">key =</span> HCIkey, </span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>                        <span class="at">num.groups =</span> <span class="dv">4</span>, </span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>                        <span class="at">item =</span> <span class="st">"all"</span></span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>                                           )</span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a><span class="do">## Make all plots have the same color scheme for response options</span></span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a><span class="do">## Also make all plots have more tick marks on the vertical axis</span></span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="fu">seq_along</span>(distractor_plots)) {</span>
<span id="cb13-16"><a href="#cb13-16" aria-hidden="true" tabindex="-1"></a>  distractor_plots[[i]] <span class="ot">&lt;-</span> distractor_plots[[i]] <span class="sc">+</span> </span>
<span id="cb13-17"><a href="#cb13-17" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="at">A =</span> <span class="st">"red"</span>,</span>
<span id="cb13-18"><a href="#cb13-18" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">B =</span> <span class="st">"green"</span>,</span>
<span id="cb13-19"><a href="#cb13-19" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">C =</span> <span class="st">"cyan"</span>,</span>
<span id="cb13-20"><a href="#cb13-20" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">D =</span> <span class="st">"blue"</span>,</span>
<span id="cb13-21"><a href="#cb13-21" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">E =</span> <span class="st">"magenta"</span>)) <span class="sc">+</span></span>
<span id="cb13-22"><a href="#cb13-22" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_y_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="at">by =</span> <span class="fl">0.1</span>),</span>
<span id="cb13-23"><a href="#cb13-23" aria-hidden="true" tabindex="-1"></a>                       <span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>))</span>
<span id="cb13-24"><a href="#cb13-24" aria-hidden="true" tabindex="-1"></a>                                        }</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>To understand the elements of a distractor plot, let us examine the distractor plot for item 1 below. The horizontal axis represents the total score, which has been grouped into 4 quantiles. Group 1 includes the lowest 25% of total scores, group 2 includes the next 25%, and so on. The vertical axis represents the proportion of test-takers who selected each response option. The correct answer, as defined by the scoring key, is shown using a solid line, while distractors are shown using dashed lines.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>distractor_plots<span class="sc">$</span>A1</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="project_1_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="384"></p>
</figure>
</div>
</div>
</div>
<p>Now let’s examine the distractor plots for all 20 items. The plots are neatly summarized into a single multi-panel figure. The legends and axis titles are omitted for visual clarity; all plots within the mosaic use the same coloring scheme described in the code above.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Combine all plots into a multi-panel figure</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">wrap_plots</span>(distractor_plots, <span class="at">ncol =</span> <span class="dv">4</span>) <span class="sc">&amp;</span> </span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">7</span>),</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.title =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">5</span>),</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">legend.position =</span> <span class="st">"none"</span></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>        )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="project_1_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" style="width:125.0%"></p>
</figure>
</div>
</div>
</div>
<p>Numerical values for the selection proportions, as well as additional statistics such as the sample size for each response option and the point-biserial correlations between each response option and the total scores, are a useful supplement to the distractor plots. The <code>DistractorAnalysis()</code> function in the <code>{ShinyItemAnalysis}</code> package will provide the selection proportions by group, but it does not provide the additional statistics. Thus, I prefer the <code>{CTT}</code> package which has a very similar function called <code>distractorAnalysis()</code>. In fact, the function in the <code>{ShinyItemAnalysis}</code> package is a modified version of the function in the <code>{CTT}</code> package, so the underlying code is very similar.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Load the CTT package</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(CTT)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="do">## Compute distractor statistics</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>DA_CTT <span class="ot">&lt;-</span> <span class="fu">distractorAnalysis</span>(</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>                <span class="at">items =</span> items_unscored,</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>                <span class="at">key =</span> HCIkey,</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>                <span class="at">nGroups =</span> <span class="dv">4</span>,</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>                <span class="at">validResp =</span> <span class="st">"fromItem"</span>,</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>                <span class="at">pTable =</span> <span class="cn">TRUE</span>,</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>                <span class="at">digits =</span> <span class="dv">2</span></span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>                             )</span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>DA_CTT</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>$A1
  correct key   n rspP  pbis discrim lower mid50 mid75 upper
A           A  29 0.04 -0.25   -0.09  0.09  0.05  0.01  0.00
B           B  62 0.09 -0.17   -0.07  0.12  0.07  0.09  0.06
C           C 113 0.17 -0.41   -0.28  0.32  0.16  0.08  0.04
D       *   D 465 0.70  0.30    0.44  0.46  0.72  0.82  0.90

$A2
  correct key   n rspP  pbis discrim lower mid50 mid75 upper
A           A  98 0.15 -0.39   -0.23  0.28  0.11  0.08  0.04
B       *   B 502 0.75  0.22    0.33  0.59  0.73  0.84  0.92
C           C  69 0.10 -0.20   -0.09  0.13  0.16  0.08  0.04

$A3
  correct key   n rspP  pbis discrim lower mid50 mid75 upper
A       *   A 567 0.85  0.34    0.32  0.67  0.83  0.97  0.99
B           B  47 0.07 -0.38   -0.16  0.16  0.07  0.01  0.00
C           C  55 0.08 -0.33   -0.16  0.17  0.10  0.02  0.01

$A4
  correct key   n rspP  pbis discrim lower mid50 mid75 upper
A           A  17 0.03 -0.27   -0.07  0.07  0.01  0.00  0.00
B           B  20 0.03 -0.26   -0.08  0.08  0.01  0.01  0.00
C           C 365 0.55 -0.28   -0.28  0.61  0.60  0.60  0.33
D       *   D 267 0.40  0.18    0.43  0.25  0.38  0.40  0.67

$A5
  correct key   n rspP  pbis discrim lower mid50 mid75 upper
A           A  71 0.11 -0.23   -0.11  0.15  0.13  0.09  0.04
B       *   B 298 0.45  0.27    0.51  0.22  0.47  0.50  0.73
C           C  99 0.15 -0.25   -0.11  0.20  0.15  0.11  0.10
D           D 201 0.30 -0.31   -0.30  0.43  0.25  0.30  0.13

$A6
  correct key   n rspP  pbis discrim lower mid50 mid75 upper
A           A  60 0.09 -0.32   -0.16  0.16  0.13  0.03  0.01
B           B 369 0.55 -0.42   -0.39  0.71  0.64  0.46  0.32
C       *   C 240 0.36  0.34    0.55  0.12  0.24  0.50  0.67

$A7
  correct key   n rspP  pbis discrim lower mid50 mid75 upper
A           A  77 0.12 -0.25   -0.14  0.17  0.11  0.11  0.03
B           B 230 0.34 -0.26   -0.15  0.40  0.40  0.31  0.24
C       *   C 362 0.54  0.11    0.29  0.43  0.49  0.57  0.73

$A8
  correct key   n rspP  pbis discrim lower mid50 mid75 upper
A           A 114 0.17 -0.38   -0.29  0.32  0.16  0.09  0.03
B           B  85 0.13 -0.35   -0.20  0.22  0.14  0.08  0.02
C       *   C 470 0.70  0.33    0.49  0.46  0.70  0.83  0.95

$A9
  correct key   n rspP  pbis discrim lower mid50 mid75 upper
A           A 315 0.47 -0.30   -0.31  0.53  0.53  0.55  0.22
B           B  54 0.08 -0.29   -0.11  0.15  0.05  0.04  0.04
C           C  13 0.02 -0.23   -0.06  0.06  0.00  0.00  0.00
D       *   D 287 0.43  0.22    0.47  0.27  0.42  0.42  0.73

$A10
  correct key   n rspP  pbis discrim lower mid50 mid75 upper
A       *   A 429 0.64  0.27    0.50  0.43  0.57  0.75  0.93
B           B 118 0.18 -0.32   -0.25  0.27  0.20  0.14  0.03
C           C 122 0.18 -0.35   -0.25  0.30  0.23  0.11  0.04

$A11
  correct key   n rspP  pbis discrim lower mid50 mid75 upper
A       *   A 515 0.77  0.29    0.37  0.58  0.75  0.89  0.96
B           B  59 0.09 -0.38   -0.19  0.19  0.08  0.03  0.00
C           C  95 0.14 -0.31   -0.18  0.23  0.18  0.08  0.04

$A12
  correct key   n rspP  pbis discrim lower mid50 mid75 upper
A           A  70 0.10 -0.28   -0.15  0.17  0.14  0.07  0.02
B           B  12 0.02 -0.14   -0.02  0.03  0.01  0.01  0.01
C           C  29 0.04 -0.21   -0.07  0.07  0.06  0.03  0.00
D       *   D 386 0.58  0.30    0.52  0.36  0.49  0.68  0.88
E           E 172 0.26 -0.34   -0.29  0.37  0.31  0.21  0.08

$A13
  correct key   n rspP  pbis discrim lower mid50 mid75 upper
A       *   A 402 0.60  0.36    0.59  0.35  0.45  0.77  0.94
B           B  52 0.08 -0.29   -0.13  0.14  0.08  0.04  0.01
C           C  94 0.14 -0.34   -0.21  0.24  0.19  0.06  0.03
D           D 121 0.18 -0.32   -0.25  0.27  0.27  0.13  0.02

$A14
  correct key   n rspP  pbis discrim lower mid50 mid75 upper
A       *   A 505 0.75  0.34    0.44  0.52  0.75  0.90  0.96
B           B  35 0.05 -0.22   -0.07  0.09  0.09  0.01  0.01
C           C  80 0.12 -0.32   -0.20  0.22  0.12  0.06  0.02
D           D  49 0.07 -0.36   -0.17  0.17  0.04  0.03  0.00

$A15
  correct key   n rspP  pbis discrim lower mid50 mid75 upper
A           A  84 0.13 -0.25   -0.12  0.21  0.10  0.07  0.08
B           B 162 0.24 -0.42   -0.35  0.39  0.33  0.15  0.04
C       *   C 291 0.43  0.31    0.57  0.21  0.32  0.53  0.79
D           D 132 0.20 -0.15   -0.09  0.19  0.25  0.25  0.10

$A16
  correct key   n rspP  pbis discrim lower mid50 mid75 upper
A       *   A 404 0.60  0.37    0.57  0.34  0.54  0.75  0.91
B           B 166 0.25 -0.43   -0.37  0.41  0.31  0.15  0.04
C           C  59 0.09 -0.33   -0.16  0.17  0.08  0.04  0.01
D           D  40 0.06 -0.15   -0.05  0.08  0.07  0.05  0.03

$A17
  correct key   n rspP  pbis discrim lower mid50 mid75 upper
A           A 204 0.30 -0.08    0.04  0.24  0.36  0.37  0.28
B           B 183 0.27 -0.30   -0.23  0.38  0.20  0.28  0.15
C       *   C 195 0.29  0.05    0.25  0.24  0.25  0.23  0.50
D           D  87 0.13 -0.14   -0.06  0.13  0.19  0.13  0.07

$A18
  correct key   n rspP  pbis discrim lower mid50 mid75 upper
A           A  46 0.07 -0.32   -0.13  0.14  0.05  0.03  0.01
B           B  70 0.10 -0.41   -0.22  0.24  0.08  0.01  0.02
C       *   C 528 0.79  0.42    0.43  0.54  0.84  0.95  0.97
D           D  25 0.04 -0.25   -0.08  0.08  0.03  0.01  0.00

$A19
  correct key   n rspP  pbis discrim lower mid50 mid75 upper
A           A  43 0.06 -0.29   -0.11  0.12  0.07  0.03  0.01
B           B  47 0.07 -0.32   -0.14  0.15  0.06  0.02  0.01
C       *   C 521 0.78  0.36    0.42  0.55  0.80  0.92  0.97
D           D  30 0.04 -0.19   -0.07  0.08  0.05  0.02  0.01
E           E  28 0.04 -0.25   -0.10  0.10  0.03  0.01  0.00

$A20
  correct key   n rspP  pbis discrim lower mid50 mid75 upper
A           A  12 0.02 -0.19   -0.05  0.05  0.01  0.00  0.00
B           B  39 0.06 -0.34   -0.14  0.14  0.03  0.02  0.00
C           C 138 0.21 -0.38   -0.28  0.33  0.22  0.14  0.06
D       *   D 480 0.72  0.34    0.46  0.48  0.74  0.84  0.94</code></pre>
</div>
</div>
<p>Now that the distractor plots and statistics for all 20 items are computed, let us examine the items for any issues with distractor functioning. First, a cursory glance at the distractor plots provides a useful overall picture of distractor functioning. Here are some useful guidelines when examining distractor plots:</p>
<ol type="1">
<li>The correct option (solid line) should trend upwards.</li>
<li>The distractors (dashed lines) should trend downwards.</li>
<li>The highest total score group should not have any distractors which are selected more frequently than the correct option.</li>
<li>Flat trendlines suggest non-discriminating distractors.</li>
<li>Very low proportion trendlines suggest non-functioning distractors.</li>
</ol>
<p>An example of an easy but well-discriminating item is item 3 (<em>p</em> = .848, RIR = .344). The correct option trends upwards, the distractors trend downwards, and the distractors are selected at a substantial proportion among lower total score groups.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>distractor_plots<span class="sc">$</span>A3</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="project_1_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="384"></p>
</figure>
</div>
</div>
</div>
<p>An example of a difficult but well-discriminating item is item 6 (<em>p</em> = .359, RIR = .345). The correct option trends upwards, the distractors trend downwards, and the distractors are selected at a substantial proportion among lower total score groups. Since this item is quite difficult, we see that lower total score groups are much more likely to select the distractor option B, and that option B retains a substantial proportion even at higher total score groups.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>distractor_plots<span class="sc">$</span>A6</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="project_1_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="384"></p>
</figure>
</div>
</div>
</div>
<p>An example of a non-functioning distractor can be found in item 12 (<em>p</em> = .577, RIR = .300). We see that distractor option B (green) is almost never selected, even in the lowest total score group. The exact proportions according to the table above are (.03, .01, .01, .01) for the 4 groups, from lowest to highest total score.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>distractor_plots<span class="sc">$</span>A12</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="project_1_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="384"></p>
</figure>
</div>
</div>
</div>
<p>Overall, the classical distractor analysis indicates that there are relatively few problematic distractors. There are a few potentially non-functional distractors, but there are no clearly non-discriminating distractors. This is expected since the instrument was developed with distractor functioning in mind. Based on overall selection proportions, the potential non-functioning distractors include:</p>
<ul>
<li>Item 1: distractor A (prop = .04).</li>
<li>Item 4: distractors A (prop = .03) and B (prop = .03).</li>
<li>Item 9: distractor C (prop = .02).</li>
<li>Item 12: distractors B (prop = .02) and C (prop = .04).</li>
<li>Item 20: distractor A (prop = .02).</li>
</ul>
<p>Earlier it was mentioned that a low overall selection proportion does not necessarily mean that the distractor is problematic. This is because the item may be an easy item, in which case low overall selection proportions are expected. Additionally, the distractor may be selected to a substantial degree by lower total score groups, but almost never selected by higher total score groups, resulting in a low overall selection proportion. Such distractors may still discriminate well, as indicated by the point-biserial correlations, even though they have a low overall selection proportion. Let us examine the potential non-functioning distractors with these considerations in mind.</p>
<p>For item 1, Distractor A has a moderate negative point-biserial correlation (<span class="math inline">\(r_{pbis}=-.25\)</span>) with the selection proportions (.09, .05, .01, .00) in order from lowest to highest total score group. Since option A discriminates fairly well and is selected at a substantial frequency by lower total score groups, this distractor is likely unproblematic and does not require revision.</p>
<p>For item 4, distractors A and B have moderate negative point-biserial correlations (<span class="math inline">\(r_{pbis}=-.27\)</span> and <span class="math inline">\(r_{pbis}=-.26\)</span>, respectively), but they are only selected at a substantial frequency by the lowest total score group, and are almost never selected by the other 3 groups. This suggests that distractors A and B are primarily selected due to chance guessing at low ability levels. Additionally, distractor C clearly dominates the response options, with the selection proportions (.61, .60, .60, .33). The distractor functioning indicates that this item is essentially dichotomous, and is consistent with the context found in the item stem, which essentially asks whether a homeostatic control mechanism is always functioning (option D) or if it only activates in certain scenarios (option C).</p>
<p>For item 9, distractor C has a moderate negative point-biserial correlation (<span class="math inline">\(r_{pbis}=-.23\)</span>) but is essentially only selected by the lowest total score group (.06, .00, .00, .00). This suggests that distractor C is primarily selected due to chance guessing at low ability levels and may require revision.</p>
<p>For item 12, distractor B has a weak negative point-biserial correlation (<span class="math inline">\(r_{pbis}=-.14\)</span>) and is essentially only selected by the lowest total score group (.03, .01, .01, .01), and distractor C has a moderate negative point-biserial correlation (<span class="math inline">\(r_{pbis}=-.21\)</span>) and is selected at a substantial frequency in the lower total score groups (.07, .06, .03, .00). This suggests that distractor B may require revision, but distractor C is likely unproblematic.</p>
<p>For item 20, distractor A has a weak negative point-biserial correlation (<span class="math inline">\(r_{pbis}=-.19\)</span>) and is essentially only selected by the lowest total score group (.05, .01, .00, .00). This suggests that distractor A is primarily selected due to chance guessing at low ability levels and may require revision. Additionally, this item is structurally similar to item 4, with the distractor functioning and item stem indicating that the item is essentially dichotomous.</p>
<p>An additional point worth noting is that some distractors (notably in item 15 and item 17) have a trendline which is peaked around the middle total score range. This suggests that these distractors are of a different type compared to those which trend downwards monotonically; rather than affecting lower ability individuals the most, individuals need to be at a certain ability level to possess the partial understanding required for these distractors to function. These distractors are not necessarily problematic and could be useful and informative. However, the functioning of these distractors is inconclusive under classical distractor analyses. More sophisticated methods, such as item response theory (IRT) approaches using the nominal response model (NRM), may better explain the functioning of these distractors.</p>
<p><em>In conclusion, the classical distractor analysis suggests that the distractors are functioning well in general. Item 9 (distractor C) and item 12 (distractor B) are infrequently selected and are essentially only selected by the group with the lowest 25% of total scores, which suggests that these distractors may be non-functioning and may benefit from revision. Additionally, the distractor functioning for item 4 and item 20 suggests that these items are essentially dichotomous, which is consistent with the context found in the item stems. These distractors may benefit from revision, or they may be retained as is, since these items still provide useful information about test-takers.</em></p>
<hr>
</section>
<section id="optimal-scaling" class="level2">
<h2 class="anchored" data-anchor-id="optimal-scaling">Optimal Scaling</h2>
<p>Thus far, the items have been dichotomously scored by assigning each correct option a score of 1 and each incorrect option a score of 0. However, it is likely that some information is lost by dichotomous scoring. This is because dichotomous scoring treats each incorrect option as having equal value, which is unlikely since the distractors differ in their quality, as seen in the classical distractor analysis above. An alternative is to use <em>optimal scaling</em>, which describes a set of data-driven approaches that assign different scores to each response option by optimizing for some statistical criterion.</p>
<p>A common statistical criterion is to choose scores which maximize the sum of item correlations (the entries in the item correlation matrix). This is equivalent to maximizing the coefficient alpha of the instrument. The <code>corAspect()</code> function in the <code>{aspect}</code> package (Mair &amp; de Leeuw, 2010) can be used to perform optimal scaling. By default, the <code>corAspect()</code> function optimizes for the sum of item correlations (<code>aspect = "aspectSum"</code>) and assumes that the variables are nominal (<code>level = "nominal"</code>).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Load the aspect package</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(aspect)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="do">## Optimizing for the sum of item correlations (and thus coefficient alpha)</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>opt_alpha <span class="ot">&lt;-</span> <span class="fu">corAspect</span>(items_unscored, <span class="at">aspect =</span> <span class="st">"aspectSum"</span>, <span class="at">level =</span> <span class="st">"nominal"</span>)</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a><span class="do">## Examining the output (rounded to 2 decimal places)</span></span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(opt_alpha<span class="sc">$</span>eigencor, <span class="dv">2</span>) <span class="co"># Eigenvalues of the correlation matrix</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 3.86 1.30 1.22 1.11 1.07 0.96 0.93 0.90 0.88 0.84 0.83 0.81 0.77 0.74 0.72
[16] 0.67 0.66 0.63 0.57 0.52</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lapply</span>(opt_alpha<span class="sc">$</span>catscores, round, <span class="dv">2</span>) <span class="co"># Optimal scores for each item</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>$A1
  score
A -2.47
B -0.23
C -1.69
D  0.60

$A2
  score
A -2.23
B  0.54
C -0.74

$A3
  score
A  0.41
B -2.91
C -1.77

$A4
  score
A -4.52
B -3.44
C -0.01
D  0.56

$A5
  score
A -1.19
B  1.10
C -1.14
D -0.64

$A6
  score
A -2.01
B -0.46
C  1.21

$A7
  score
A -2.25
B -0.49
C  0.79

$A8
  score
A -1.38
B -1.73
C  0.65

$A9
  score
A -0.08
B -2.24
C -4.39
D  0.71

$A10
  score
A  0.74
B -1.17
C -1.49

$A11
  score
A  0.50
B -2.72
C -1.04

$A12
  score
A -1.49
B -2.13
C -2.11
D  0.80
E -0.69

$A13
  score
A  0.79
B -1.83
C -1.35
D -0.78

$A14
  score
A  0.55
B -1.41
C -1.30
D -2.53

$A15
  score
A -1.03
B -1.37
C  0.97
D  0.19

$A16
  score
A  0.77
B -1.01
C -2.07
D -0.51

$A17
  score
A  1.00
B -1.55
C  0.34
D  0.14

$A18
  score
A -1.93
B -1.87
C  0.52
D -2.11

$A19
  score
A -1.83
B -2.13
C  0.53
D -1.31
E -2.03

$A20
  score
A -3.23
B -2.65
C -0.92
D  0.56</code></pre>
</div>
</div>
<p>Additionally, the total scores based on optimal scores can be computed, and the relationship between the total scores can be examined by computing the correlation and creating a scatterplot.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Compute optimal total scores</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>total_scores_opt <span class="ot">&lt;-</span> <span class="fu">unname</span>(<span class="fu">rowSums</span>(opt_alpha<span class="sc">$</span>scoremat))</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a><span class="do">## Compare optimal and dichotomous total scores</span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">cor</span>(total_scores, total_scores_opt), <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.95</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(total_scores, total_scores_opt)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="project_1_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Now let us interpret the results of the optimal scaling procedure. Looking at the eigenvalues, we see that there the first eigenvalue (3.86) is much larger than subsequent eigenvalues (1.30, 1.22, 1.11, …). This suggests that the dataset is unidimensional. Additional dimensionality checks will be performed in a later section.</p>
<p>Looking at the optimal scores (category scores) for each item, we see that, in general, the positive values are quite modest (~0.50 to ~1.10), while the negative values can be quite extreme (e.g.&nbsp;-4.52). This is because distractors which are selected very infrequently can have inflated scores due to having very small sample sizes for those groups.</p>
<p>Furthermore, we see that, in general, the correct option has the most positive value. The only exception to this is item 17, in which the correct answer C is given an optimal score of 0.34, while the distractor A has a higher score of 1.00. This suggests that individuals who selected the distractor tended to do better on the other 19 items compared to individuals who selected the correct answer. This suggests that item 17 is problematic.</p>
<p>Additionally, the correlation between the total scores using dichotomous or optimal scoring is around 0.95, which suggests that the two scoring methods agree on about 90% of the variance in how individuals are rank-ordered. This suggests that there is not much to be gained from optimal scoring.</p>
<p><em>In conclusion, the results of the optimal scoring procedure suggests that (1) item 17 is problematic, since the distractor option A was given a higher score (1.00) than the correct answer C (0.34), (2) not much is gained from optimal scoring, since the correlation between the total scores using both scoring approaches is around 0.95, which suggests a shared variance of around 90%, and (3) the data is unidimensional, since there is one dominant eigenvalue.</em></p>
<hr>
</section>
<section id="dimensionality-analysis" class="level2">
<h2 class="anchored" data-anchor-id="dimensionality-analysis">Dimensionality Analysis</h2>
<p>The dimensionality of the dataset can be examined using factor analysis. Before performing factor analysis, the Kaiser-Meyer-Olkin (KMO) index is a useful measure of how well-suited a dataset is for factor analysis. Here, the KMO index is calculated using the tetrachoric correlation matrix rather than the raw item responses (Pearson correlations), which is more appropriate since the items are dichotomously scored but are hypothesized to reflect an underlying continuous attribute. In fact, using Pearson correlations results in a slightly higher KMO index, but it is not shown here.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">KMO</span>(tetra<span class="sc">$</span>rho)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Kaiser-Meyer-Olkin factor adequacy
Call: KMO(r = tetra$rho)
Overall MSA =  0.78
MSA for each item = 
 QR1  QR2  QR3  QR4  QR5  QR6  QR7  QR8  QR9 QR10 QR11 QR12 QR13 QR14 QR15 QR16 
0.74 0.72 0.85 0.63 0.87 0.86 0.62 0.88 0.63 0.86 0.89 0.77 0.74 0.78 0.89 0.87 
QR17 QR18 QR19 QR20 
0.40 0.73 0.71 0.81 </code></pre>
</div>
</div>
<p>The overall MSA is 0.78, which is acceptable but not particularly strong. Kaiser and Rice (1974) suggested that the overall MSA should exceed .50 as a bare minimum for a correlation matrix to be suitable for factor analysis. The overall MSA is lowered by a few items with low individual MSAs: item 17 (.40), item 7 (.62), item 4 (.63), and item 9 (.63).</p>
<p>Next, the number of factors can be determined using parallel analysis. Parallel analysis compares the eigenvalues from the actual dataset against eigenvalues from simulated/resampled datasets of the same size. The idea is that a “real” factor should explain more variance than would be expected from chance alone.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fa.parallel</span>(items_scored, <span class="at">fm =</span> <span class="st">"ml"</span>, <span class="at">cor =</span> <span class="st">"tet"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="project_1_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Parallel analysis suggests that the number of factors =  7  and the number of components =  3 </code></pre>
</div>
</div>
<p>The parallel analysis results suggest that there are 7 factors and 3 components. PCA analyzes total variance in each variable, so PCA eigenvalues tend to be larger and drop off faster. FA analyzes only the common variance between variables, so FA eigenvalues tend to be smaller and drop off more gradually. In this case, both results suggest that the dataset may have additional structure beyond a single construct. However, the eigenvalues clearly indicate that there is one dominant factor/component which is much larger than the others. This suggests that, even though additional factors may explain a significant amount of variance, the dataset is essentially unidimensional.</p>
<p>Next, we can fit EFA models with a different number of factors to compare their model fit. This will provide additional evidence about the dimensionality of the dataset. Since the parallel analysis suggested 3 components and 7 factors, all solutions up to 7 factors will be compared.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Fit EFA models</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>fit_fa_1 <span class="ot">&lt;-</span> <span class="fu">fa</span>(items_scored, <span class="at">nfactors =</span> <span class="dv">1</span>, <span class="at">fm =</span> <span class="st">"ml"</span>, <span class="at">cor =</span> <span class="st">"tet"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>fit_fa_2 <span class="ot">&lt;-</span> <span class="fu">fa</span>(items_scored, <span class="at">nfactors =</span> <span class="dv">2</span>, <span class="at">fm =</span> <span class="st">"ml"</span>, <span class="at">cor =</span> <span class="st">"tet"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>fit_fa_3 <span class="ot">&lt;-</span> <span class="fu">fa</span>(items_scored, <span class="at">nfactors =</span> <span class="dv">3</span>, <span class="at">fm =</span> <span class="st">"ml"</span>, <span class="at">cor =</span> <span class="st">"tet"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>fit_fa_4 <span class="ot">&lt;-</span> <span class="fu">fa</span>(items_scored, <span class="at">nfactors =</span> <span class="dv">4</span>, <span class="at">fm =</span> <span class="st">"ml"</span>, <span class="at">cor =</span> <span class="st">"tet"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>fit_fa_5 <span class="ot">&lt;-</span> <span class="fu">fa</span>(items_scored, <span class="at">nfactors =</span> <span class="dv">5</span>, <span class="at">fm =</span> <span class="st">"ml"</span>, <span class="at">cor =</span> <span class="st">"tet"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>fit_fa_6 <span class="ot">&lt;-</span> <span class="fu">fa</span>(items_scored, <span class="at">nfactors =</span> <span class="dv">6</span>, <span class="at">fm =</span> <span class="st">"ml"</span>, <span class="at">cor =</span> <span class="st">"tet"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>fit_fa_7 <span class="ot">&lt;-</span> <span class="fu">fa</span>(items_scored, <span class="at">nfactors =</span> <span class="dv">7</span>, <span class="at">fm =</span> <span class="st">"ml"</span>, <span class="at">cor =</span> <span class="st">"tet"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Create a table with fit statistics rounded to 3 decimal places</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>fit_fa_list <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="at">f1 =</span> fit_fa_1, </span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>                    <span class="at">f2 =</span> fit_fa_2, </span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>                    <span class="at">f3 =</span> fit_fa_3, </span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>                    <span class="at">f4 =</span> fit_fa_4,</span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>                    <span class="at">f5 =</span> fit_fa_5,</span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a>                    <span class="at">f6 =</span> fit_fa_6,</span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a>                    <span class="at">f7 =</span> fit_fa_7)</span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-10"><a href="#cb39-10" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">t</span>(<span class="fu">sapply</span>(fit_fa_list, <span class="cf">function</span>(m) <span class="fu">c</span>(</span>
<span id="cb39-11"><a href="#cb39-11" aria-hidden="true" tabindex="-1"></a>      <span class="at">chisq =</span> m<span class="sc">$</span>STATISTIC,</span>
<span id="cb39-12"><a href="#cb39-12" aria-hidden="true" tabindex="-1"></a>      <span class="at">df    =</span> m<span class="sc">$</span>dof,</span>
<span id="cb39-13"><a href="#cb39-13" aria-hidden="true" tabindex="-1"></a>      <span class="at">RMSEA =</span> m<span class="sc">$</span>RMSEA[<span class="dv">1</span>],</span>
<span id="cb39-14"><a href="#cb39-14" aria-hidden="true" tabindex="-1"></a>      <span class="at">RMSR  =</span> m<span class="sc">$</span>rms,</span>
<span id="cb39-15"><a href="#cb39-15" aria-hidden="true" tabindex="-1"></a>      <span class="at">TLI   =</span> m<span class="sc">$</span>TLI,</span>
<span id="cb39-16"><a href="#cb39-16" aria-hidden="true" tabindex="-1"></a>      <span class="at">BIC   =</span> m<span class="sc">$</span>BIC</span>
<span id="cb39-17"><a href="#cb39-17" aria-hidden="true" tabindex="-1"></a>      ))), <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>      chisq  df RMSEA.RMSEA  RMSR   TLI      BIC
f1 1273.675 170       0.098 0.075 0.614  167.692
f2  979.778 151       0.091 0.061 0.673   -2.596
f3  753.615 133       0.084 0.055 0.722 -111.654
f4  572.516 116       0.077 0.045 0.765 -182.155
f5  417.208 100       0.069 0.038 0.811 -233.370
f6  297.901  85       0.061 0.032 0.850 -255.091
f7  220.098  71       0.056 0.029 0.874 -241.813</code></pre>
</div>
</div>
<p>We see that the fit indices all improve monotonically as the number of factors increases, which is to be expected. Interestingly, the Bayesian Information Criterion (BIC) favors the 6-factor solution. The BIC rewards better model fit but also penalizes for increased complexity. A more negative BIC indicates a better model fit given its degree of complexity. We see that the BIC drops sharply at the beginning and continues to decrease until it hits a minimum in the 6-factor solution, before increasing again with the 7-factor solution. However, the BIC is not a perfect indicator of which solution should be retained. It’s a good idea to look at the factor loadings to see if they make sense.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(fit_fa_6<span class="sc">$</span>loadings, <span class="at">cutoff =</span> <span class="fl">0.2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Loadings:
     ML1    ML6    ML3    ML4    ML5    ML2   
QR1   0.334         0.212                     
QR2                                      0.948
QR3   0.293                              0.356
QR4                        0.540              
QR5                                           
QR6   0.575                                   
QR7   0.202                                   
QR8   0.311  0.298                            
QR9                        0.866              
QR10  0.267                                   
QR11  0.377                                   
QR12  0.652                                   
QR13                              0.973       
QR14                1.000                     
QR15                0.214                     
QR16  0.411                       0.202       
QR17                                          
QR18         0.963                            
QR19  0.291  0.556                            
QR20                0.250  0.444              

                 ML1   ML6   ML3   ML4   ML5   ML2
SS loadings    1.620 1.505 1.214 1.300 1.191 1.182
Proportion Var 0.081 0.075 0.061 0.065 0.060 0.059
Cumulative Var 0.081 0.156 0.217 0.282 0.341 0.401</code></pre>
</div>
</div>
<p>We see that a few items load almost exclusively on a single factor: item 14 (1.000), item 13 (.973), item 18 (.963), item 2 (.948), item 9 (.866). This is not a good sign and indicates that the data does not actually support having 6 factors. A few of the factors are likely just 1-2 items which have been treated as a factor. Let’s look at the communalities for the items.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>fit_fa_6<span class="sc">$</span>communalities</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       QR1        QR2        QR3        QR4        QR5        QR6        QR7 
0.30099260 0.89476711 0.42057334 0.29527801 0.15678732 0.39276190 0.05772399 
       QR8        QR9       QR10       QR11       QR12       QR13       QR14 
0.30481475 0.76299149 0.21722781 0.29205659 0.42655099 0.99500000 0.99500000 
      QR15       QR16       QR17       QR18       QR19       QR20 
0.23488792 0.33491815 0.04072255 0.99500000 0.48310281 0.40916915 </code></pre>
</div>
</div>
<p>We see that a few items (13, 14, and 18) have communalities equal to exactly .995. These are likely <em>Heywood cases</em>, in which a communality reaches or exceeds 1.0. The <code>{psych}</code> package caps it at .995 to prevent it from actually exceeding 1.0, which would be an impossible value. Additionally, we see that some items have extremely low communalities: item 7 (.058) and item 17 (.041). Thus, the 6-factor solution is almost certainly incorrect.</p>
<p>Looking at the communalities for the other solutions, the 5-factor, 4-factor, 3-factor, and 2-factor solutions all contain at least 1 Heywood case. The 1-factor solution is also problematic, as some items have extremely low communalities: item 4 (.043), item 7 (.024), item 9 (.082), and item 17 (.003). These items are the same ones that had a low MSA when calculating the KMO index.</p>
<p><em>In conclusion, the dimensionality of the instrument is inconclusive. EFA solutions with 1 to 7 factors were compared. The fit statistics improved monotonically as the number of factors increased and the BIC favored the 6-factor solution. However, examination of the factor loadings and communalities indicated that all solutions except for the 1-factor solution contained Heywood cases. Additionally, a few items (4, 7, 9, and 17) were consistently found to have extremely low communalities. This suggests that these items are problematic and may need to be removed before dimensionality can be accurately assessed. However, for the purposes of subsequent IRT analyses, the dataset may be treated as essentially unidimensional, since there is one clearly dominant factor.</em></p>
<hr>
</section>
<section id="item-response-theory-analysis" class="level2">
<h2 class="anchored" data-anchor-id="item-response-theory-analysis">Item Response Theory Analysis</h2>
<p>The <code>{mirt}</code> package can be used to fit 1PL (Rasch), 2PL, and 3PL IRT models.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Load mirt package</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mirt)</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a><span class="do">## Fit IRT models</span></span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>fit_1PL <span class="ot">&lt;-</span> <span class="fu">mirt</span>(items_scored, <span class="at">model =</span> <span class="dv">1</span>, <span class="at">itemtype =</span> <span class="st">"Rasch"</span>)</span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a>fit_2PL <span class="ot">&lt;-</span> <span class="fu">mirt</span>(items_scored, <span class="at">model =</span> <span class="dv">1</span>, <span class="at">itemtype =</span> <span class="st">"2PL"</span>)</span>
<span id="cb45-7"><a href="#cb45-7" aria-hidden="true" tabindex="-1"></a>fit_3PL <span class="ot">&lt;-</span> <span class="fu">mirt</span>(items_scored, <span class="at">model =</span> <span class="dv">1</span>, <span class="at">itemtype =</span> <span class="st">"3PL"</span>, </span>
<span id="cb45-8"><a href="#cb45-8" aria-hidden="true" tabindex="-1"></a>                  <span class="at">technical =</span> <span class="fu">list</span>(<span class="at">NCYCLES =</span> <span class="dv">2000</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>We see that the 1PL (Rasch) and 2PL models converged quickly, but that the 3PL model took a large number of iterations (1372) to converge. This may be due to an insufficient sample size (N=669) for stable parameter estimates, and may indicate that the 3PL estimation is too unstable to be used. Let us examine the 3PL estimation further by looking at the item parameters.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">coef</span>(fit_3PL, <span class="at">IRTpars =</span> <span class="cn">TRUE</span>, <span class="at">simplify =</span> <span class="cn">TRUE</span>)<span class="sc">$</span>items, <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>        a     b    g u
QR1  1.04 -0.44 0.25 1
QR2  0.73 -1.61 0.03 1
QR3  2.45 -0.67 0.47 1
QR4  0.36  1.26 0.01 1
QR5  0.69  0.37 0.01 1
QR6  1.47  0.85 0.10 1
QR7  0.22 -0.64 0.01 1
QR8  1.11 -0.96 0.00 1
QR9  0.45  0.68 0.00 1
QR10 3.66  0.54 0.48 1
QR11 1.30 -0.52 0.39 1
QR12 2.29  0.60 0.38 1
QR13 4.59  0.35 0.36 1
QR14 3.34  0.06 0.53 1
QR15 2.01  0.81 0.23 1
QR16 1.65  0.16 0.27 1
QR17 1.47  2.86 0.27 1
QR18 1.85 -1.10 0.00 1
QR19 1.44 -1.05 0.10 1
QR20 0.88 -1.19 0.02 1</code></pre>
</div>
</div>
<p>We see that some items have implausibly high discriminations: item 10 (3.66), item 13 (4.59), and item 14 (3.34). Furthermore, we also see that some items have implausibly low guessing parameters: item 2 (.03), item 4 (.01), item 5 (.01), item 6 (.10), item 7 (.01), item 8 (.00), item 9 (.00), item 18 (.00), item 19 (.10), and item 20 (.02). Thus, the 3PL estimation is likely too unstable to be used. We will proceed with the 1PL (Rasch) and 2PL models.</p>
<p>Next, the item parameters from the 1PL (Rasch) and 2PL models are summarized in the following table.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>IRT_results <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">b_1PL =</span> <span class="fu">round</span>(<span class="fu">coef</span>(fit_1PL, <span class="at">IRTpars =</span> <span class="cn">TRUE</span>, <span class="at">simplify =</span> <span class="cn">TRUE</span>)<span class="sc">$</span>items[, <span class="st">"b"</span>], <span class="dv">2</span>),</span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">b_2PL =</span> <span class="fu">round</span>(<span class="fu">coef</span>(fit_2PL, <span class="at">IRTpars =</span> <span class="cn">TRUE</span>, <span class="at">simplify =</span> <span class="cn">TRUE</span>)<span class="sc">$</span>items[, <span class="st">"b"</span>], <span class="dv">2</span>),</span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">a_2PL =</span> <span class="fu">round</span>(<span class="fu">coef</span>(fit_2PL, <span class="at">IRTpars =</span> <span class="cn">TRUE</span>, <span class="at">simplify =</span> <span class="cn">TRUE</span>)<span class="sc">$</span>items[, <span class="st">"a"</span>], <span class="dv">2</span>)</span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a>IRT_results</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     b_1PL b_2PL a_2PL
QR1  -0.94 -1.10  0.87
QR2  -1.25 -1.71  0.71
QR3  -1.93 -1.54  1.54
QR4   0.47  1.19  0.35
QR5   0.25  0.34  0.69
QR6   0.66  0.68  1.02
QR7  -0.19 -0.72  0.23
QR8  -0.98 -1.00  1.06
QR9   0.33  0.65  0.46
QR10 -0.67 -0.81  0.84
QR11 -1.37 -1.45  1.00
QR12 -0.36 -0.43  0.84
QR13 -0.47 -0.45  1.20
QR14 -1.28 -1.21  1.18
QR15  0.30  0.33  0.91
QR16 -0.49 -0.49  1.10
QR17  1.01  7.40  0.12
QR18 -1.50 -1.13  1.80
QR19 -1.43 -1.24  1.36
QR20 -1.06 -1.16  0.95</code></pre>
</div>
</div>
<p>Notably, item 17 has a very high difficulty (b = 7.40) and a very low discrimination (a = .12) under the 2PL model. This is the most clearly problematic item.</p>
<p>Looking at the item discriminations under the 2PL model, we see that there is a wide range of values (.12 to 1.80). Looking at the descriptive statistics below, we see that the item discriminations have a mean of .91 and a standard deviation of .42, which is a substantial amount of variation. This suggests that the equal-discrimination assumption underlying the 1PL (Rasch) model may be untenable for this dataset.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">describe</span>(<span class="fu">coef</span>(fit_2PL, <span class="at">IRTpars =</span> <span class="cn">TRUE</span>, <span class="at">simplify =</span> <span class="cn">TRUE</span>)<span class="sc">$</span>items[, <span class="st">"a"</span>])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   vars  n mean   sd median trimmed  mad  min max range  skew kurtosis   se
X1    1 20 0.91 0.42   0.93    0.91 0.34 0.12 1.8  1.67 -0.01    -0.43 0.09</code></pre>
</div>
</div>
<p>Now let us compare the fit of the 1PL (Rasch) and 2PL models. Since the models are nested, a likelihood ratio test (LRT) can be performed and relative model fit statistics can be obtained. Furthermore, absolute model fit statistics can be obtained by calculating the M2 index, which is specifically designed to compare IRT models. Additionally, item fit can be compared by calculating the S-X<span class="math inline">\(^2\)</span> statistics for each item.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Relative fit statistics</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(fit_1PL, fit_2PL)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>             AIC    SABIC       HQ      BIC    logLik      X2 df p
fit_1PL 15754.85 15782.79 15791.50 15849.47 -7856.423             
fit_2PL 15613.51 15666.74 15683.33 15793.75 -7766.757 179.332 19 0</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Absolute fit statistics</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a><span class="fu">M2</span>(fit_1PL)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>           M2  df p RMSEA RMSEA_5 RMSEA_95 SRMSR   TLI  CFI
stats 530.586 189 0 0.052   0.047    0.057 0.073 0.839 0.84</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">M2</span>(fit_2PL)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>          M2  df p RMSEA RMSEA_5 RMSEA_95 SRMSR   TLI   CFI
stats 331.72 170 0 0.038   0.032    0.044 0.047 0.915 0.924</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Item fit statistics</span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a><span class="fu">itemfit</span>(fit_1PL)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   item   S_X2 df.S_X2 RMSEA.S_X2 p.S_X2
1   QR1 13.795      13      0.010  0.388
2   QR2 18.938      13      0.026  0.125
3   QR3 23.007      13      0.034  0.042
4   QR4 31.471      12      0.049  0.002
5   QR5 13.548      12      0.014  0.330
6   QR6 14.378      13      0.013  0.348
7   QR7 60.012      13      0.074  0.000
8   QR8 16.844      13      0.021  0.207
9   QR9 22.773      12      0.037  0.030
10 QR10 28.663      13      0.042  0.007
11 QR11  5.067      12      0.000  0.956
12 QR12 16.451      13      0.020  0.226
13 QR13 30.189      13      0.044  0.004
14 QR14 17.589      13      0.023  0.174
15 QR15 12.078      12      0.003  0.439
16 QR16 16.864      13      0.021  0.206
17 QR17 76.822      13      0.086  0.000
18 QR18 29.524      12      0.047  0.003
19 QR19 25.802      12      0.041  0.011
20 QR20 10.592      13      0.000  0.645</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">itemfit</span>(fit_2PL)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   item   S_X2 df.S_X2 RMSEA.S_X2 p.S_X2
1   QR1 15.246      13      0.016  0.292
2   QR2 17.623      13      0.023  0.172
3   QR3 11.381      11      0.007  0.412
4   QR4 14.176      14      0.004  0.437
5   QR5 13.448      13      0.007  0.414
6   QR6 14.133      12      0.016  0.292
7   QR7 22.093      13      0.032  0.054
8   QR8 15.620      12      0.021  0.209
9   QR9 14.697      13      0.014  0.327
10 QR10 24.253      13      0.036  0.029
11 QR11  4.070      12      0.000  0.982
12 QR12 14.443      13      0.013  0.343
13 QR13 25.126      12      0.040  0.014
14 QR14 11.853      12      0.000  0.458
15 QR15 10.253      12      0.000  0.594
16 QR16 12.331      13      0.000  0.501
17 QR17 11.980      14      0.000  0.608
18 QR18  8.338      11      0.000  0.683
19 QR19 16.342      12      0.023  0.176
20 QR20  9.373      12      0.000  0.671</code></pre>
</div>
</div>
<p>In terms of relative fit, the LRT is significant (<span class="math inline">\(\chi^2\)</span> = 179.33, df = 19, p &lt; .001), which indicates that the more complex model (2PL) fits significantly better than the less complex model (1PL/Rasch). The information criteria all agree with this result, with the 2PL model having a lower AIC by about 141 points and a lower BIC by about 56 points.</p>
<p>In terms of absolute fit, the 2PL model fits better according to every statistic: the M2 is about 199 points lower for the 2PL model, the SRMSR for the 2PL is .047 (compared to .073 for the 1PL), and the TLI and CFI are .915 and .924, respectively. According to conventional guidelines (SRMSR &lt; .05, TLI &gt; .90, CFI &gt; .90), the 2PL model has good fit, while the 1PL model has inadequate fit.</p>
<p>In terms of item fit, a significant result (<span class="math inline">\(\alpha\)</span> = .05) in the S-X<span class="math inline">\(^2\)</span> test indicates a misfitting item. Since the S-X<span class="math inline">\(^2\)</span> test is sensitive to sample size, it is also a good idea to look at the RMSEA for an effect size measure (conventional guideline is RMSEA &lt; .05 indicates good fit). For the 1PL model, items 3, 4, 7, 9, 10, 13, 17, 18, and 19 show statistically significant misfit, and items 7 and 17 show practically significant misfit. For the 2PL model, items 10 and 13 show statistically significant misfit, and no items show practically significant misfit. Thus, the 2PL model has much better item fit than the 1PL (Rasch) model.</p>
<p>Next, let us check how well the local independence assumptions holds under both models. This can be done using Yen’s Q3 statistic.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">residuals</span>(fit_1PL, <span class="at">type =</span> <span class="st">"Q3"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Q3 summary statistics:
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
 -0.153  -0.078  -0.042  -0.037  -0.002   0.216 

        QR1    QR2    QR3    QR4    QR5    QR6    QR7    QR8    QR9   QR10
QR1   1.000  0.012 -0.008 -0.090 -0.067  0.040 -0.074 -0.043 -0.068 -0.024
QR2   0.012  1.000  0.146 -0.025  0.006 -0.063 -0.098  0.024 -0.111 -0.113
QR3  -0.008  0.146  1.000 -0.104 -0.008 -0.022 -0.094  0.082 -0.100 -0.016
QR4  -0.090 -0.025 -0.104  1.000 -0.056 -0.111 -0.061 -0.055  0.192 -0.145
QR5  -0.067  0.006 -0.008 -0.056  1.000 -0.048 -0.031  0.006 -0.098 -0.047
QR6   0.040 -0.063 -0.022 -0.111 -0.048  1.000 -0.038  0.033 -0.134  0.026
QR7  -0.074 -0.098 -0.094 -0.061 -0.031 -0.038  1.000 -0.046 -0.007 -0.153
QR8  -0.043  0.024  0.082 -0.055  0.006  0.033 -0.046  1.000 -0.111 -0.083
QR9  -0.068 -0.111 -0.100  0.192 -0.098 -0.134 -0.007 -0.111  1.000 -0.102
QR10 -0.024 -0.113 -0.016 -0.145 -0.047  0.026 -0.153 -0.083 -0.102  1.000
QR11 -0.079 -0.133  0.011 -0.070 -0.067 -0.015 -0.067 -0.030 -0.081 -0.002
QR12  0.044 -0.053 -0.018 -0.050 -0.070  0.087 -0.060 -0.068 -0.134 -0.021
QR13 -0.143 -0.062  0.015 -0.141 -0.034 -0.015 -0.143 -0.040 -0.136  0.058
QR14  0.038 -0.087 -0.033 -0.098 -0.027 -0.050 -0.106 -0.077 -0.074  0.025
QR15 -0.018  0.015 -0.026 -0.062 -0.056 -0.094 -0.096 -0.070 -0.125  0.009
QR16 -0.005 -0.013 -0.028 -0.058 -0.026 -0.012 -0.119 -0.015 -0.069 -0.047
QR17 -0.082 -0.081 -0.085  0.000 -0.068 -0.104 -0.003 -0.104  0.020 -0.041
QR18 -0.014  0.015  0.056 -0.106 -0.011 -0.038 -0.100  0.079  0.020 -0.032
QR19 -0.064 -0.082  0.021 -0.145 -0.068 -0.024 -0.001  0.025 -0.047 -0.028
QR20 -0.042 -0.070 -0.022  0.042 -0.105 -0.017 -0.041 -0.056  0.140 -0.070
       QR11   QR12   QR13   QR14   QR15   QR16   QR17   QR18   QR19   QR20
QR1  -0.079  0.044 -0.143  0.038 -0.018 -0.005 -0.082 -0.014 -0.064 -0.042
QR2  -0.133 -0.053 -0.062 -0.087  0.015 -0.013 -0.081  0.015 -0.082 -0.070
QR3   0.011 -0.018  0.015 -0.033 -0.026 -0.028 -0.085  0.056  0.021 -0.022
QR4  -0.070 -0.050 -0.141 -0.098 -0.062 -0.058  0.000 -0.106 -0.145  0.042
QR5  -0.067 -0.070 -0.034 -0.027 -0.056 -0.026 -0.068 -0.011 -0.068 -0.105
QR6  -0.015  0.087 -0.015 -0.050 -0.094 -0.012 -0.104 -0.038 -0.024 -0.017
QR7  -0.067 -0.060 -0.143 -0.106 -0.096 -0.119 -0.003 -0.100 -0.001 -0.041
QR8  -0.030 -0.068 -0.040 -0.077 -0.070 -0.015 -0.104  0.079  0.025 -0.056
QR9  -0.081 -0.134 -0.136 -0.074 -0.125 -0.069  0.020  0.020 -0.047  0.140
QR10 -0.002 -0.021  0.058  0.025  0.009 -0.047 -0.041 -0.032 -0.028 -0.070
QR11  1.000  0.033  0.059 -0.018 -0.041  0.015 -0.057 -0.001  0.020 -0.056
QR12  0.033  1.000 -0.049 -0.008 -0.072  0.038 -0.122 -0.151  0.002 -0.105
QR13  0.059 -0.049  1.000  0.080  0.028  0.045 -0.080  0.077 -0.072  0.013
QR14 -0.018 -0.008  0.080  1.000  0.050 -0.052 -0.125 -0.042  0.020  0.095
QR15 -0.041 -0.072  0.028  0.050  1.000 -0.009 -0.078  0.003 -0.012 -0.062
QR16  0.015  0.038  0.045 -0.052 -0.009  1.000 -0.099 -0.037 -0.010 -0.071
QR17 -0.057 -0.122 -0.080 -0.125 -0.078 -0.099  1.000 -0.093 -0.045 -0.078
QR18 -0.001 -0.151  0.077 -0.042  0.003 -0.037 -0.093  1.000  0.216 -0.009
QR19  0.020  0.002 -0.072  0.020 -0.012 -0.010 -0.045  0.216  1.000 -0.059
QR20 -0.056 -0.105  0.013  0.095 -0.062 -0.071 -0.078 -0.009 -0.059  1.000</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">residuals</span>(fit_2PL, <span class="at">type =</span> <span class="st">"Q3"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Q3 summary statistics:
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
 -0.208  -0.075  -0.040  -0.036  -0.001   0.245 

        QR1    QR2    QR3    QR4    QR5    QR6    QR7    QR8    QR9   QR10
QR1   1.000  0.021 -0.048 -0.033 -0.051  0.029 -0.011 -0.059 -0.022 -0.026
QR2   0.021  1.000  0.135  0.019  0.023 -0.063 -0.048  0.021 -0.070 -0.112
QR3  -0.048  0.135  1.000 -0.057 -0.017 -0.064 -0.034  0.016 -0.076 -0.041
QR4  -0.033  0.019 -0.057  1.000  0.007 -0.046 -0.009  0.000  0.245 -0.090
QR5  -0.051  0.023 -0.017  0.007  1.000 -0.045  0.028  0.010 -0.041 -0.037
QR6   0.029 -0.063 -0.064 -0.046 -0.045  1.000  0.035  0.004 -0.083  0.005
QR7  -0.011 -0.048 -0.034 -0.009  0.028  0.035  1.000  0.020  0.048 -0.098
QR8  -0.059  0.021  0.016  0.000  0.010  0.004  0.020  1.000 -0.069 -0.104
QR9  -0.022 -0.070 -0.076  0.245 -0.041 -0.083  0.048 -0.069  1.000 -0.059
QR10 -0.026 -0.112 -0.041 -0.090 -0.037  0.005 -0.098 -0.104 -0.059  1.000
QR11 -0.088 -0.134 -0.048 -0.020 -0.061 -0.037 -0.009 -0.063 -0.044 -0.013
QR12  0.048 -0.044 -0.041  0.010 -0.053  0.071  0.004 -0.081 -0.082 -0.025
QR13 -0.184 -0.083 -0.066 -0.083 -0.045 -0.081 -0.076 -0.106 -0.097  0.021
QR14  0.017 -0.097 -0.118 -0.043 -0.026 -0.089 -0.040 -0.130 -0.036  0.005
QR15 -0.025  0.016 -0.055  0.000 -0.048 -0.136 -0.031 -0.095 -0.074 -0.006
QR16 -0.021 -0.015 -0.097  0.007 -0.021 -0.054 -0.042 -0.058 -0.019 -0.070
QR17 -0.018 -0.035 -0.008  0.050 -0.002 -0.022  0.022 -0.032  0.076  0.021
QR18 -0.077 -0.014 -0.119 -0.057 -0.031 -0.106 -0.030 -0.018  0.052 -0.075
QR19 -0.102 -0.102 -0.093 -0.094 -0.077 -0.069  0.068 -0.042 -0.014 -0.057
QR20 -0.038 -0.057 -0.075  0.102 -0.084 -0.026  0.031 -0.076  0.185 -0.070
       QR11   QR12   QR13   QR14   QR15   QR16   QR17   QR18   QR19   QR20
QR1  -0.088  0.048 -0.184  0.017 -0.025 -0.021 -0.018 -0.077 -0.102 -0.038
QR2  -0.134 -0.044 -0.083 -0.097  0.016 -0.015 -0.035 -0.014 -0.102 -0.057
QR3  -0.048 -0.041 -0.066 -0.118 -0.055 -0.097 -0.008 -0.119 -0.093 -0.075
QR4  -0.020  0.010 -0.083 -0.043  0.000  0.007  0.050 -0.057 -0.094  0.102
QR5  -0.061 -0.053 -0.045 -0.026 -0.048 -0.021 -0.002 -0.031 -0.077 -0.084
QR6  -0.037  0.071 -0.081 -0.089 -0.136 -0.054 -0.022 -0.106 -0.069 -0.026
QR7  -0.009  0.004 -0.076 -0.040 -0.031 -0.042  0.022 -0.030  0.068  0.031
QR8  -0.063 -0.081 -0.106 -0.130 -0.095 -0.058 -0.032 -0.018 -0.042 -0.076
QR9  -0.044 -0.082 -0.097 -0.036 -0.074 -0.019  0.076  0.052 -0.014  0.185
QR10 -0.013 -0.025  0.021  0.005 -0.006 -0.070  0.021 -0.075 -0.057 -0.070
QR11  1.000  0.027  0.014 -0.056 -0.057 -0.016  0.006 -0.091 -0.034 -0.068
QR12  0.027  1.000 -0.085 -0.023 -0.083  0.024 -0.051 -0.208 -0.022 -0.098
QR13  0.014 -0.085  1.000  0.015 -0.021 -0.023  0.005 -0.030 -0.167 -0.023
QR14 -0.056 -0.023  0.015  1.000  0.027 -0.104 -0.049 -0.171 -0.057  0.071
QR15 -0.057 -0.083 -0.021  0.027  1.000 -0.040 -0.001 -0.041 -0.045 -0.065
QR16 -0.016  0.024 -0.023 -0.104 -0.040  1.000 -0.013 -0.144 -0.077 -0.090
QR17  0.006 -0.051  0.005 -0.049 -0.001 -0.013  1.000 -0.001  0.035 -0.005
QR18 -0.091 -0.208 -0.030 -0.171 -0.041 -0.144 -0.001  1.000  0.086 -0.088
QR19 -0.034 -0.022 -0.167 -0.057 -0.045 -0.077  0.035  0.086  1.000 -0.107
QR20 -0.068 -0.098 -0.023  0.071 -0.065 -0.090 -0.005 -0.088 -0.107  1.000</code></pre>
</div>
</div>
<p>The mean Q3 for the 1PL (Rasch) and 2PL models are -.037 and -.036, respectively, which are small. Additionally, the first and third quartiles are (-.078, -.002) for the 1PL (Rasch) model and (-.075, -.001) for the 2PL model. This indicates that, for the majority of items, there are no issues with local dependence. However, the large maximum values (.216 for the 1PL model and .245 for the 2PL model) indicate that there are item pairs with substantial dependence. To find the largest entries, the <code>suppress =</code> argument can be used to remove entries below a certain magnitude. A practical guideline is that a Q3 which is 0.20 above the mean should be flagged.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">residuals</span>(fit_1PL, <span class="at">type =</span> <span class="st">"Q3"</span>, <span class="at">suppress =</span> .<span class="dv">20</span> <span class="sc">-</span> .<span class="dv">037</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Q3 summary statistics:
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
 -0.153  -0.078  -0.042  -0.037  -0.002   0.216 

     QR1 QR2 QR3   QR4 QR5 QR6 QR7 QR8   QR9 QR10 QR11 QR12 QR13 QR14 QR15 QR16
QR1    1                                                                       
QR2        1                                                                   
QR3            1                                                               
QR4              1.000                 0.192                                   
QR5                      1                                                     
QR6                          1                                                 
QR7                              1                                             
QR8                                  1                                         
QR9              0.192                 1.000                                   
QR10                                            1                              
QR11                                                 1                         
QR12                                                      1                    
QR13                                                           1               
QR14                                                                1          
QR15                                                                     1     
QR16                                                                          1
QR17                                                                           
QR18                                                                           
QR19                                                                           
QR20                                                                           
     QR17  QR18  QR19 QR20
QR1                       
QR2                       
QR3                       
QR4                       
QR5                       
QR6                       
QR7                       
QR8                       
QR9                       
QR10                      
QR11                      
QR12                      
QR13                      
QR14                      
QR15                      
QR16                      
QR17    1                 
QR18      1.000 0.216     
QR19      0.216 1.000     
QR20                     1</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">residuals</span>(fit_2PL, <span class="at">type =</span> <span class="st">"Q3"</span>, <span class="at">suppress =</span> .<span class="dv">20</span> <span class="sc">-</span> .<span class="dv">036</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Q3 summary statistics:
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
 -0.208  -0.075  -0.040  -0.036  -0.001   0.245 

        QR1 QR2 QR3   QR4 QR5 QR6 QR7 QR8   QR9 QR10 QR11   QR12   QR13   QR14
QR1   1.000                                                      -0.184       
QR2           1                                                               
QR3               1                                                           
QR4                 1.000                 0.245                               
QR5                         1                                                 
QR6                             1                                             
QR7                                 1                                         
QR8                                     1                                     
QR9                 0.245                 1.000                               
QR10                                               1                          
QR11                                                    1                     
QR12                                                       1.000              
QR13 -0.184                                                       1.000       
QR14                                                                     1.000
QR15                                                                          
QR16                                                                          
QR17                                                                          
QR18                                                      -0.208        -0.171
QR19                                                             -0.167       
QR20                                      0.185                               
     QR15 QR16 QR17   QR18   QR19  QR20
QR1                                    
QR2                                    
QR3                                    
QR4                                    
QR5                                    
QR6                                    
QR7                                    
QR8                                    
QR9                               0.185
QR10                                   
QR11                                   
QR12                -0.208             
QR13                       -0.167      
QR14                -0.171             
QR15    1                              
QR16         1                         
QR17              1                    
QR18                 1.000             
QR19                        1.000      
QR20                              1.000</code></pre>
</div>
</div>
<p>For the 1PL model, we see that there is substantial dependence between item 4 and item 9, as well as between item 18 and item 19. For the 2PL model, we see that there is substantial dependence between item 4 and item 9, as well as between item 9 and item 20. The item stems for these item pairs may be worth examining for local dependence.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>